import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "voiddevs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Ortak arka plan efektleri */}
        <div className="pointer-events-none absolute inset-0 z-0">
          <div
            className="absolute inset-0"
            style={{
              background:
                "radial-gradient(ellipse 60% 40% at 20% 20%, #a259ff44 0%, #1a102a 60%, transparent 100%)",
            }}
          ></div>
          <div
            className="absolute inset-0"
            style={{
              background:
                "radial-gradient(ellipse 40% 30% at 80% 80%, #a78bfa22 0%, transparent 80%)",
            }}
          ></div>
          <div
            className="absolute inset-0"
            style={{
              background:
                "linear-gradient(to right, rgba(255,255,255,0.03) 1px, transparent 1px), linear-gradient(to bottom, rgba(255,255,255,0.03) 1px, transparent 1px)",
              backgroundSize: "120px 120px",
            }}
          />
        </div>
        <div style={{ minHeight: 'calc(100vh - 5rem)' }}>
          {children}
        </div>
      </body>
    </html>
  );
}
